name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Bootstrap
      run: ./bootstrap.sh

    - name: Configure
      run: ./configure

    - name: Make dist
      run: make dist

    - name: Upload dist to Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: obstack-*.tar.gz
        tag: ${{ github.ref }}
        file_glob: true
